# Generated by Django 3.1.6 on 2021-03-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_authors',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_books',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='genres',
            field=models.CharField(blank=True, choices=[('crime', 'Crime'), ('biography', 'Biography'), ('business', 'Business'), ('romance', 'Romance'), ('horror', 'Horror'), ('mindset', 'Mindset'), ('children', 'Children')], max_length=20),
        ),
    ]
