# Generated by Django 3.1.6 on 2021-03-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210316_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_authors',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_books',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='genres',
            field=models.CharField(blank=True, choices=[('mindset', 'Mindset'), ('biography', 'Biography'), ('horror', 'Horror'), ('crime', 'Crime'), ('business', 'Business'), ('children', 'Children'), ('romance', 'Romance')], max_length=20),
        ),
        migrations.DeleteModel(
            name='BookPreferences',
        ),
    ]
