# Generated by Django 3.1.6 on 2021-03-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210316_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='genres',
            field=models.CharField(blank=True, choices=[('horror', 'Horror'), ('crime', 'Crime'), ('children', 'Children'), ('biography', 'Biography'), ('romance', 'Romance'), ('mindset', 'Mindset'), ('business', 'Business')], default='Genres', max_length=20),
        ),
    ]
