# Generated by Django 3.1.6 on 2021-03-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210317_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='genres',
            field=models.CharField(blank=True, choices=[('mindset', 'Mindset'), ('business', 'Business'), ('horror', 'Horror'), ('romance', 'Romance'), ('crime', 'Crime'), ('children', 'Children'), ('biography', 'Biography')], default='Random Genres', max_length=20),
        ),
    ]
