# Generated by Django 3.1.6 on 2021-03-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20210317_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='genres',
            field=models.CharField(blank=True, choices=[('crime', 'Crime'), ('random_genres', 'Random Genres'), ('mindset', 'Mindset'), ('children', 'Children'), ('biography', 'Biography'), ('horror', 'Horror'), ('business', 'Business'), ('romance', 'Romance')], default='random_genres', max_length=20),
        ),
    ]
