# Generated by Django 3.1.6 on 2021-03-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20210317_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='genres',
            field=models.CharField(blank=True, choices=[('mindset', 'Mindset'), ('romance', 'Romance'), ('horror', 'Horror'), ('biography', 'Biography'), ('random_genres', 'Random Genres'), ('business', 'Business'), ('children', 'Children'), ('crime', 'Crime')], default='random_genres', max_length=20),
        ),
    ]
