# Generated by Django 3.1.6 on 2021-03-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20210322_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='genres',
            field=models.CharField(choices=[('random_genres', 'Random Genres'), ('mindset', 'Mindset'), ('business', 'Business'), ('biography', 'Biography'), ('romance', 'Romance'), ('crime', 'Crime'), ('horror', 'Horror'), ('children', 'Children')], default='random_genres', max_length=20),
        ),
    ]
