# Generated by Django 3.1.6 on 2023-01-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20210322_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='genres',
            field=models.CharField(choices=[('random_genres', 'Random Genres'), ('art', 'Art'), ('biography', 'Biography'), ('business', 'Business'), ('children', 'Children'), ('crime', 'Crime'), ('health', 'Health'), ('romance', 'Romance'), ('mindset', 'Mindset'), ('horror', 'Horror')], default='random_genres', max_length=20),
        ),
    ]
