# Generated by Django 3.1.6 on 2021-03-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('introduction', models.TextField(max_length=600)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('biannual', 'Biannual'), ('annually', 'Annually')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Pricing',
            },
        ),
    ]
