# Generated by Django 3.1.6 on 2021-02-20 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricing',
            options={'verbose_name_plural': 'Pricing'},
        ),
    ]
