# Generated by Django 3.1.6 on 2021-02-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_auto_20210220_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('biannual', 'Biannual'), ('yearly', 'Yearly')], max_length=20),
        ),
    ]
