# Generated by Django 3.1.6 on 2021-02-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_auto_20210226_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('biannual', 'Biannual'), ('annually', 'Annually')], max_length=20),
        ),
    ]
