# Generated by Django 3.1.6 on 2021-03-01 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pricing', '0005_auto_20210301_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres', models.CharField(blank=True, choices=[('mindset', 'Mindset'), ('romance', 'Romance'), ('horror', 'Horror'), ('crime', 'Crime'), ('children', 'Children'), ('business', 'Business'), ('biography', 'Biography')], max_length=20, null=True)),
                ('favorite_authors', models.CharField(blank=True, max_length=100, null=True)),
                ('favorite_books', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
