# Generated by Django 3.1.6 on 2021-03-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0007_auto_20210301_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpreferences',
            name='genres',
            field=models.CharField(blank=True, choices=[('children', 'Children'), ('mindset', 'Mindset'), ('biography', 'Biography'), ('business', 'Business'), ('horror', 'Horror'), ('crime', 'Crime'), ('romance', 'Romance')], max_length=20, null=True),
        ),
    ]
