# Generated by Django 3.1.6 on 2021-03-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0008_auto_20210303_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpreferences',
            name='genres',
            field=models.CharField(blank=True, choices=[('crime', 'Crime'), ('business', 'Business'), ('horror', 'Horror'), ('biography', 'Biography'), ('mindset', 'Mindset'), ('children', 'Children'), ('romance', 'Romance')], max_length=20, null=True),
        ),
    ]
