# Generated by Django 3.1.6 on 2021-03-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0009_auto_20210303_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpreferences',
            name='genres',
            field=models.CharField(blank=True, choices=[('children', 'Children'), ('crime', 'Crime'), ('romance', 'Romance'), ('biography', 'Biography'), ('mindset', 'Mindset'), ('horror', 'Horror'), ('business', 'Business')], max_length=20, null=True),
        ),
    ]
