# Generated by Django 3.1.6 on 2021-03-04 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pricing', '0010_auto_20210304_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpreferences',
            name='genres',
            field=models.CharField(blank=True, choices=[('biography', 'Biography'), ('business', 'Business'), ('children', 'Children'), ('horror', 'Horror'), ('crime', 'Crime'), ('mindset', 'Mindset'), ('romance', 'Romance')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bookpreferences',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
