# Generated by Django 3.1.6 on 2021-03-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0012_auto_20210304_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookpreferences',
            old_name='default_favorite_authors',
            new_name='favorite_authors',
        ),
        migrations.RenameField(
            model_name='bookpreferences',
            old_name='default_favorite_books',
            new_name='favorite_books',
        ),
        migrations.RemoveField(
            model_name='bookpreferences',
            name='default_genres',
        ),
        migrations.AddField(
            model_name='bookpreferences',
            name='genres',
            field=models.CharField(blank=True, choices=[('horror', 'Horror'), ('children', 'Children'), ('crime', 'Crime'), ('mindset', 'Mindset'), ('romance', 'Romance'), ('biography', 'Biography'), ('business', 'Business')], max_length=20, null=True),
        ),
    ]
