# Generated by Django 3.1.6 on 2021-03-09 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0013_auto_20210304_1142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookPreferences',
        ),
    ]
