# Generated by Django 3.1.6 on 2021-03-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='end_date',
            field=models.DateTimeField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='plan_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='start_date',
            field=models.DateTimeField(blank=True, max_length=80, null=True),
        ),
    ]
