# Generated by Django 3.1.6 on 2021-02-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='postcode',
            new_name='post_code',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='street_adrdress1',
            new_name='street_address1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='street_adrdress2',
        ),
        migrations.AddField(
            model_name='order',
            name='street_address2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
