# Generated by Django 3.1.6 on 2021-02-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20210223_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='lineitem_total',
            field=models.DecimalField(decimal_places=2, default=5, editable=False, max_digits=6),
            preserve_default=False,
        ),
    ]
